"""telmekom


Revision ID: 9db2cfa0c5b2
Revises: 246dcc203f57
Create Date: 2020-11-16 21:48:53.373787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9db2cfa0c5b2'
down_revision = '246dcc203f57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('id_ombis', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('org_unit', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'org_unit')
    op.drop_column('users', 'id_ombis')
    op.drop_column('users', 'data')
    # ### end Alembic commands ###
