"""options

Revision ID: e0c726dc259a
Revises: 9db2cfa0c5b2
Create Date: 2020-11-29 20:16:25.469292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0c726dc259a'
down_revision = '9db2cfa0c5b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('options_users',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_options_users_created'), 'options_users', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_options_users_created'), table_name='options_users')
    op.drop_table('options_users')
    # ### end Alembic commands ###
